apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-argo-set
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: example-argo-dev
      - cluster: qa
        url: https://kubernetes.default.svc
        namespace: example-argo-qa
  template:
    metadata:
      name: '{{cluster}}-example-argo-set'
    spec:
      project: default
      source:
        repoURL: https://github.com/bcovieswex/argocd-example.git
        targetRevision: main
        path: example-proj-2
        helm:
          valueFiles:
            - environments/{{cluster}}.yaml
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true