apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-argo
  namespace: argocd
spec:
  project: zen-devtest
  source:
    repoURL: https://github.com/bcovieswex/argocd-example.git
    targetRevision: main
    path: example-proj-1
  destination:
    server: https://kubernetes.default.svc
    namespace: example-argo
