apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: httpd
    image: httpd:{{ .Values.httpd.imageTag }}
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc